import 'package:khushi_creation/model/cloth_item_model.dart';
import 'package:flutter/material.dart';

List<ClothItemModel> clothItemModel = [
  ClothItemModel(
    id: 1,
    style: "Men's Style",
    imagePath: 'assets/images/man/man1.jpg',
    name: 'T-Shirt',
    icon: Icon(
      Icons.star,
      color: Colors.amber,
    ),
    rating: 4.5,
    price: 250.99,
    categories: ['Newest', 'Man'],
    wishListCategories: ['T-Shirt'],
    isFavourite: false,
  ),
  ClothItemModel(
      id: 2,
      style: "Men's Style",
      imagePath: 'assets/images/man/man2.jpg',
      name: 'Jacket',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 450.99,
      categories: ['Popular', 'Man'],
      wishListCategories: ['Jacket'],
      isFavourite: false),
  ClothItemModel(
      id: 3,
      style: "Female's Style",
      imagePath: 'assets/images/woman/woman1.jpg',
      name: 'Dress',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 450.99,
      categories: ['Popular', 'Woman'],
      wishListCategories: ['Dress'],
      isFavourite: false),
  ClothItemModel(
      id: 4,
      style: "Men's Style",
      imagePath: 'assets/images/man/man3.jpg',
      name: 'Pants',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 999.99,
      categories: ['Newest', 'Man'],
      wishListCategories: ['Pants'],
      isFavourite: false),
  ClothItemModel(
      id: 5,
      style: "Female's Style",
      imagePath: 'assets/images/woman/woman2.jpg',
      name: 'Dress',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 1500.99,
      categories: ['Newest', 'Woman'],
      wishListCategories: ['Dress'],
      isFavourite: false),
  ClothItemModel(
    id: 6,
    style: "Men's Style",
    imagePath: 'assets/images/man/man4.jpg',
    name: 'T-Shirt',
    icon: Icon(
      Icons.star,
      color: Colors.amber,
    ),
    rating: 4.5,
    price: 250.99,
    categories: ['Newest', 'Man'],
    wishListCategories: ['T-Shirt'],
    isFavourite: false,
  ),
  ClothItemModel(
      id: 7,
      style: "Men's Style",
      imagePath: 'assets/images/man/man5.jpg',
      name: 'Jacket',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 450.99,
      categories: ['Popular', 'Man'],
      wishListCategories: ['Jacket'],
      isFavourite: false),
  ClothItemModel(
      id: 8,
      style: "Female's Style",
      imagePath: 'assets/images/woman/woman3.jpg',
      name: 'Dress',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 450.99,
      categories: ['Popular', 'Woman'],
      wishListCategories: ['Dress'],
      isFavourite: false),
  ClothItemModel(
      id: 9,
      style: "Female's Style",
      imagePath: 'assets/images/woman/woman4.jpg',
      name: 'Top',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 999.99,
      categories: ['Newest', 'Woman'],
      wishListCategories: ['Pants'],
      isFavourite: false),
  ClothItemModel(
      id: 10,
      style: "Female's Style",
      imagePath: 'assets/images/woman/woman5.jpg',
      name: 'Dress',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 1500.99,
      categories: ['Newest', 'Woman'],
      wishListCategories: ['Dress'],
      isFavourite: false),
  ClothItemModel(
      id: 11,
      style: "Female's Style",
      imagePath: 'assets/images/woman/woman6.jpg',
      name: 'Dress',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 1500.99,
      categories: ['Newest', 'Woman'],
      wishListCategories: ['Dress'],
      isFavourite: false),
  ClothItemModel(
    id: 12,
    style: "Men's Style",
    imagePath: 'assets/images/man/man6.png',
    name: 'T-Shirt',
    icon: Icon(
      Icons.star,
      color: Colors.amber,
    ),
    rating: 4.5,
    price: 250.99,
    categories: ['Newest', 'Man'],
    wishListCategories: ['T-Shirt'],
    isFavourite: false,
  ),
  ClothItemModel(
      id: 13,
      style: "Men's Style",
      imagePath: 'assets/images/man/man7.jpg',
      name: 'Jacket',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 450.99,
      categories: ['Popular', 'Man'],
      wishListCategories: ['Jacket'],
      isFavourite: false),
  ClothItemModel(
      id: 14,
      style: "Female's Style",
      imagePath: 'assets/images/woman/woman7.jpg',
      name: 'Dress',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 450.99,
      categories: ['Popular', 'Woman'],
      wishListCategories: ['Dress'],
      isFavourite: false),
  ClothItemModel(
      id: 15,
      style: "Female's Style",
      imagePath: 'assets/images/woman/woman8.jpg',
      name: 'Crop Top',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 999.99,
      categories: ['Newest', 'Woman'],
      wishListCategories: ['Dress'],
      isFavourite: false),
  ClothItemModel(
      id: 16,
      style: "Female's Style",
      imagePath: 'assets/images/woman/woman9.jpg',
      name: 'Dress',
      icon: Icon(
        Icons.star,
        color: Colors.amber,
      ),
      rating: 4.5,
      price: 1500.99,
      categories: ['Newest', 'Woman'],
      wishListCategories: ['Dress'],
      isFavourite: false),
];
